---
abstract: 'Lib of DB Query'
author:
  - '-2008, Yahoo! China Relevance Team, Alibaba Inc. All rights reserved.'
  - 'Cnangel <cnangel@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Base: 0.1
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
  Module::Install: 0
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBQuery
no_index:
  directory:
    - inc
    - t
requires:
  DBI: 1.4
  perl: 5.6.0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=DBQuery
  homepage: http://my.huhoo.net/study
  license: http://opensource.org/licenses/BSD-3-Clause
version: '1.20'
